import type { SxProps } from '@mui/material'
import { Stack, Toolbar } from '@mui/material'
import Head from 'next/head'
import React from 'react'
import SiteHeader from './SiteHeader'
import { env } from '~/env.mjs'

type Props = {
  children: React.ReactNode,
  title?: string,
  sx?: SxProps
}

const PageContainer = ({
  children,

  title = "Home",

  sx,
}: Props) => {
  return (
    <>
      <Head>
        <title>{`${title} | ${env.NEXT_PUBLIC_APP_NAME}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack justifyContent="start" alignItems="stretch" sx={{width: 1, height: "100vh"}}>
        <SiteHeader />
        {/* <SiteTopNav /> */}
        {/* <SiteTopNavTabs /> */}

        <Stack justifyContent="center" alignItems="center" sx={{width: 1, height: 1, ...sx}}>
          <Toolbar variant="dense" />
          {children}
        </Stack>
      </Stack>
    </>
  )
}

export { PageContainer }