import { Stack } from '@mui/material'
import Head from 'next/head'
import React from 'react'
import SiteHeader from './SiteHeader'
import SiteTopNav from './SiteTopNav'
import { env } from '~/env.mjs'

type Props = {
  children: React.ReactNode,
  title?: string,
  sx?: {}
}

const PageContainer = ({
  children,

  title,

  sx,
}: Props) => {
  return (
    <>
      <Head>
        <title>{title ? `${title} | ${env.NEXT_PUBLIC_APP_NAME}` : env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SiteHeader />
      {/* <SiteTopNav /> */}

      <Stack justifyContent="center" alignItems="center" sx={{width: 1, height: "100vh", ...sx}}>
        {children}
      </Stack>
    </>
  )
}

export { PageContainer }